# Generated by Django 2.1.2 on 2020-03-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
