# Generated by Django 2.1.2 on 2020-03-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=60)),
                ('AddressRoomNo', models.CharField(max_length=60)),
                ('AddressHall', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet2.Profile'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet2.Profile'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet2.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet2.Profile'),
        ),
        migrations.AlterField(
            model_name='userinterestedevents',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet2.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
