# Generated by Django 2.1.2 on 2020-03-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0002_auto_20200316_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
