# Generated by Django 2.1.2 on 2020-03-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0003_auto_20200316_2154'),
        ('meet2', '0002_auto_20200316_2359'),
    ]

    operations = [
    ]
