# Generated by Django 2.1.2 on 2020-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0004_merge_20200317_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=200),
        ),
    ]
