# Generated by Django 2.1.2 on 2020-03-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0005_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
